// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwhoejeqlidoiludvzjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3aG9lamVxbGlkb2lsdWR2emp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NDYwODMsImV4cCI6MjA2ODAyMjA4M30.39joh2Fpx2JHgve2HiICzI9p4FrkOqG43Xa6ihPI03c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});